site_name: 任务管理 CLI 文档
site_description: 任务管理命令行工具的官方文档
site_url: https://umitakahashi723.github.io/task-cli-docs/
repo_url: https://github.com/umitakahashi723/task-cli-
site_author: 你的名字
theme:
  name: material
  custom_dir: docs/theme
  palette:
    primary: blue
    accent: orange
  font:
    text: 'Roboto'
    code: 'Monospace'
  logo: images/logo.png
  icon:
    favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.expand
  language: zh
  direction: ltr
  content_overlap: true
  navigation_depth: 2
doc_dir: docs
site_dir: site
nav:
  - 首页: index.md
  - 快速入门:
      - 安装指南: installation.md
      - 使用方法: usage.md
  - 功能特性:
      - 优先级管理: priority.md
      - 任务状态: status.md
  - 贡献指南: CONTRIBUTING.md
  - 联系我们: contact.md
